# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TechArmie_capstone1_FitME' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TechArmie_capstone1_FitME

  pod 'IQKeyboardManagerSwift'
  pod 'Toast-Swift'
  
  pod 'FirebaseAuth'
  pod 'GoogleSignIn'
  
  pod 'SwiftyJSON'
  pod 'Alamofire'
  
  pod 'AWSCore'
  pod 'AWSS3'
  pod 'SDWebImage', '~> 4.0'
  
  pod 'NVActivityIndicatorView/Extended'
  pod 'IBAnimatable'
  
end
